name = "midas_node"
version = "0.1.0"
target = "javascript"

description = "Run midas tasks in a nodejs environment. "
licences = ["Apache-2.0"]
repository = { type = "github", user = "midas-framework", repo = "midas_node" }
links = [{ title = "midas", href = "https://github.com/midas-framework/midas" }]

[dependencies]
gleam_fetch = ">= 1.0.0 and < 2.0.0"
gleam_javascript = ">= 0.8.0 and < 1.0.0"
gleam_json = ">= 1.0.0 and < 3.0.0"
gleam_package_interface = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 1.7.0 and < 2.0.0"
snag = ">= 0.3.0 and < 1.0.0"
glen_node = {path= "../glen_node"}
plinth = ">= 0.4.14 and < 1.0.0"
midas = ">= 0.4.7 and < 1.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"
glen = ">= 2.2.0 and < 3.0.0"


[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
